const fs = require("fs");
const path = require("path");
const { execFile } = require("child_process");
const { getSetting } = require("./db");

const STAGE_DIR = path.join(__dirname, "data", "staging");

// گاردهای NAT که بیشترین علت خرابی تماس در شبکه‌های واقعی‌اند
const NAT_OPTS = `rtp_symmetric=yes
force_rport=yes
rewrite_contact=yes`;

function buildPjsipConf() {
  const mode = getSetting("sip_mode", "A");
  const host = getSetting("sip_pbx_host", "");
  const ext = getSetting("sip_extension", "100");
  const pass = getSetting("sip_password", "");
  const port = getSetting("sip_port", "5060");

  const header = `; Auto-generated by Jarchi panel. Manual edits will be overwritten.

[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0:${port}
`;

  if (mode === "A") {
    // line=true : تماس‌های ورودی از سانترال، خودکار به همین endpoint
    // نسبت داده می‌شوند (رفع خطای 503 — دیگر فقط به تطبیق IP متکی نیستیم)
    return `${header}
[pbx_registration]
type=registration
transport=transport-udp
outbound_auth=pbx_auth
server_uri=sip:${host}
client_uri=sip:${ext}@${host}
retry_interval=20
max_retries=0
expiration=3600
line=true
endpoint=pbx_endpoint

[pbx_auth]
type=auth
auth_type=userpass
username=${ext}
password=${pass}

[pbx_aor]
type=aor
contact=sip:${host}
qualify_frequency=30

[pbx_identify]
type=identify
endpoint=pbx_endpoint
match=${host}

[pbx_endpoint]
type=endpoint
transport=transport-udp
context=paging-in
disallow=all
allow=ulaw
allow=alaw
allow=gsm
outbound_auth=pbx_auth
aors=pbx_aor
from_user=${ext}
direct_media=no
${NAT_OPTS}
`;
  }

  // ---------- حالت B: این سرور خودش سانترال کوچک است ----------
  // شش اکانت گوشی (101 تا 106) با «همان پسورد پنل» ساخته می‌شود؛
  // گوشی‌ها با یکی از این شماره‌ها رجیستر می‌شوند و برای پیج، شماره
  // ${ext} (یا در واقع هر شماره‌ای) را می‌گیرند.
  let out = header;
  for (let n = 101; n <= 106; n++) {
    out += `
[${n}-endpoint]
type=endpoint
transport=transport-udp
context=paging-in
disallow=all
allow=ulaw
allow=alaw
allow=gsm
auth=${n}-auth
aors=${n}-aor
direct_media=no
${NAT_OPTS}

[${n}-auth]
type=auth
auth_type=userpass
username=${n}
password=${pass}

[${n}-aor]
type=aor
max_contacts=2
remove_existing=yes
`;
  }
  return out;
}

function buildExtensionsConf() {
  const ext = getSetting("sip_extension", "100");
  const maxSec = Number(getSetting("sip_max_page_seconds", "120")) || 120;

  // هر تماسی که به این context برسد (شماره پیج، s، یا هر شماره
  // دیگری که سانترال بفرستد) به منطق پیج هدایت می‌شود — رفع
  // مواردی که سانترال شماره را متفاوت ارسال می‌کند.
  return `; Auto-generated by Jarchi panel. Manual edits will be overwritten.
[paging-in]
exten => ${ext},1,Goto(jarchi-page,start,1)
exten => s,1,Goto(jarchi-page,start,1)
exten => _[0-9*#].,1,Goto(jarchi-page,start,1)

[jarchi-page]
exten => start,1,NoOp(== Jarchi paging call from \${CALLERID(num)} ==)
 same => n,Answer()
 same => n,Wait(1)
 same => n,Playback(beep)
 same => n,System(echo "\${EPOCH},\${CALLERID(num)},start" >> /var/log/paging/pages.log)
 same => n,Set(PAGEFIFO=/tmp/paging/page_audio.sln)
 same => n,System(mkfifo \${PAGEFIFO} 2>/dev/null; true)
 same => n,MixMonitor(\${PAGEFIFO})
 same => n,Wait(${maxSec})
 same => n,StopMixMonitor()
 same => n,Hangup()

exten => h,1,System(echo "\${EPOCH},\${CALLERID(num)},end" >> /var/log/paging/pages.log)
 same => n,System(rm -f /tmp/paging/page_audio.sln 2>/dev/null; mkfifo /tmp/paging/page_audio.sln 2>/dev/null; true)
`;
}

function applySipConfig() {
  return new Promise((resolve, reject) => {
    fs.mkdirSync(STAGE_DIR, { recursive: true });
    fs.writeFileSync(path.join(STAGE_DIR, "pjsip_paging.conf"), buildPjsipConf());
    fs.writeFileSync(path.join(STAGE_DIR, "extensions_paging.conf"), buildExtensionsConf());
    execFile("sudo", ["/opt/jarchi/scripts/apply-sip-config.sh"], { timeout: 30000 },
      (err, stdout, stderr) => {
        if (err) return reject(new Error(stderr || err.message));
        resolve(stdout.trim());
      });
  });
}

module.exports = { applySipConfig, buildPjsipConf, buildExtensionsConf };
